---
- name: Generate containerd default configuration
  ansible.builtin.shell: containerd config default
  register: containerd_config_output

- name: Write containerd configuration to /etc/containerd/config.toml
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_config_output.stdout }}"
    owner: root
    group: root
    mode: '0644'

- name: Update SystemdCgroup to true in containerd config
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
  notify: restart containerd



- name: Load kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
  with_items:
    - br_netfilter
    - overlay


- name: Ensure kernel modules are loaded
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay

