- name: unlink old resolv conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: copy new resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: remove old license
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- name: remove old kubernetes repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Disable Swap
  ansible.builtin.shell:
    cmd: swapoff -a

- name: Ensure swap is disabled in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: '# \g<0>'

- name: install dependency
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg

- name: get k8s license
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kuber_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add k8s apt repo
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kuber_version }}/deb/ /'
    state: present
    filename: kubernetes

- name: install kube pack
  ansible.builtin.apt:
    name: '{{ item  }}'
    state: present
    update_cache: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Ensure kubelet service is enabled
  ansible.builtin.service:
    name: kubelet
    enabled: 'yes'
